server:
  port: 8080
  # Reconoce nativamente si la petición original venía por HTTPS desde Nginx/Cloud/Proxy
  forward-headers-strategy: native

application:
  security:
    cookie:
      secure: ${COOKIE_SECURE:true}
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}

  scheduler:
    generate-occurrences: ${SCHEDULER_CRON}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: INFO