package com.example.SplitLoop.common.exception;

public enum ErrorCode {


    //GROUP//
    USER_NOT_FOUND,
    USER_ALREADY_IN_GROUP,
    GROUP_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INSUFFICIENT_PERMISSIONS,
    USER_NOT_IN_GROUP,
    LAST_ADMIN_IN_GROUP,
    CANNOT_REMOVE_GROUP_CREATOR,
    CANNOT_CHANGE_GROUP_CREATOR_ROLE,
    ONLY_GROUP_CREATOR_CAN_DELETE,

    //BALANCE//
    MEMBER_HAS_PENDING_DEBTS,
    GROUP_HAS_ACTIVE_EXPENSES,
    GROUP_HAS_UNSETTLED_EXPENSES,

    //EXPENSE//
    PARTICIPANTS_CANNOT_BE_EMPTY,
    DUPLICATED_PARTICIPANT,
    USER_NOT_MEMBER_OF_GROUP,
    RECURRING_EXPENSE_NOT_FOUND,
    EXPENSE_OCCURRENCE_NOT_FOUND,
    OCCURRENCE_ALREADY_CANCELLED,
    CANNOT_CANCEL_PAID_OCCURRENCE,
    CANNOT_CANCEL_PARTIALLY_PAID_OCCURRENCE,
    CANNOT_MODIFY_PAID_OCCURRENCE,
    RECURRING_EXPENSE_ALREADY_PAUSED,
    RECURRING_EXPENSE_ALREADY_ACTIVE,
    OCCURRENCE_NOT_CANCELLED,
    CANNOT_MODIFY_PARTIALLY_PAID_OCCURRENCE,
    SAME_PAID_BY,
    RECURRING_EXPENSE_INACTIVE,
    EXPENSE_OCCURRENCE_SPLIT_NOT_FOUND,

    //PAYMENTS//
    PAYMENT_EXCEEDS_DEBT,
    REFUND_EXCEEDS_PAYMENT,
    PAYMENT_NOT_FOUND,

    //AUTH//
    INVALID_REFRESH_TOKEN,
    INVALID_BEARER_TOKEN,

    //USER//
    INVALID_PASSWORD,
    PASSWORDS_DO_NOT_MATCH,
    SAME_PASSWORD,
    WEAK_PASSWORD,
    PASSWORD_REQUIRED,
    SAME_USERNAME,
    USERNAME_REQUIRED,
    NOTHING_TO_UPDATE,

    INVALID_TOKEN,
    USER_BLOCKED,

    ORDER_NOT_FOUND,
    INSUFFICIENT_STOCK,

    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}